#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
export LUA_PATH="${SCRIPT_DIR}/?/init.lua;${SCRIPT_DIR}/?.lua;${LUA_PATH:-}"

if [ -z "$LUA_EXEC" ]; then
    export LUA_EXEC=lua
fi

"$LUA_EXEC" "${SCRIPT_DIR}/cli.lua" "$@"
